version: '3.7'

volumes:
  library.db.volume:
    name: library.db.volume

services:
  db:
    image: mysql:5.7.21
    container_name: library.db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - library.db.volume:/var/lib/mysql
      - ./etc/sql:/docker-entrypoint-initdb.d

  web:
    build: ./etc/web
    container_name: library.web
    command: >
      bash -c "./manage.py runserver 0.0.0.0:8000 & celery -A library worker -l info -c 4"
    volumes:
      - ./library:/app
      - ./static:/static
    ports:
      - 8000:8000
      - 8888:10080
    depends_on:
      - db
      - redis

  redis:
    image: redis:4.0.10
    ports:
    - 6379:6379
